packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.8.2
  "@trpc/server": ^11.5.0
  better-auth: ^1.3.28
  ai: ^5.0.49
  "@ai-sdk/google": ^2.0.13
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  tsdown: ^0.15.5
  "@trpc/client": ^11.5.0
  drizzle-orm: ^0.44.2
